name: LeaderSystem
main: com.ericlam.mc.main.LeaderSystem
version: 1.0.0
author: Hydranapse_
depend: [HyperNiteMC-Core]
api-version: 1.13
commands:
  leadersystem:
    aliases: [leadersys, leader, leaderboard]
    description: leadersystem command