name: LeaderSystem
main: com.ericlam.mc.leadersystem.main.LeaderSystem
version: "1.3.2"
author: Hydranapse_
depend: [HyperNiteMC-Core]
api-version: "1.13"
commands:
  leadersystem:
    aliases: [leadersys, leader, leaderboard]
    description: leadersystem command